
#Adaptive Performance Tweaks: Spawn
["Exotic Birds Spawn Config"]
	Enabled = true
	Id = "exoticbirds"
	#Range: 1 ~ 64
	MaxPassiveMobsPerPlayer = 4
	#Range: 1 ~ 512
	MaxPassiveMobsPerWorld = 16
	#Range: 1 ~ 1024
	MaxPassiveMobsPerServer = 64
	#List of passive Mobs to optimize in the format ["minecraft:bat", "minecraft:cat", ..]
	PassiveMobsList = ["exoticbirds:peafowl", "exoticbirds:hummingbird", "exoticbirds:woodpecker", "exoticbirds:kingfisher", "exoticbirds:roadrunner", "exoticbirds:toucan", "exoticbirds:swan", "exoticbirds:macaw", "exoticbirds:cassowary", "exoticbirds:magpie", "exoticbirds:flamingo", "exoticbirds:kiwi", "exoticbirds:owl", "exoticbirds:pelican", "exoticbirds:lyrebird", "exoticbirds:ostrich", "exoticbirds:gouldianfinch", "exoticbirds:gull", "exoticbirds:pigeon", "exoticbirds:duck", "exoticbirds:penguin", "exoticbirds:heron", "exoticbirds:booby", "exoticbirds:bluejay", "exoticbirds:cardinal", "exoticbirds:robin", "exoticbirds:crane", "exoticbirds:kookaburra", "exoticbirds:budgerigar", "exoticbirds:cockatoo", "exoticbirds:fire_phoenix", "exoticbirds:cloud_phoenix", "exoticbirds:water_phoenix", "exoticbirds:nether_phoenix", "exoticbirds:skeleton_phoenix", "exoticbirds:snowy_phoenix", "exoticbirds:desert_phoenix", "exoticbirds:ender_phoenix", "exoticbirds:twilight_phoenix"]

